# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spells', '0001_initial'),
        ('rules', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentbonus',
            name='damage_resistance_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bonus_damage_resistance_type', to='rules.DamageType'),
        ),
        migrations.AddField(
            model_name='equipmentbonus',
            name='damage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bonus_damage_type', to='rules.DamageType'),
        ),
        migrations.AddField(
            model_name='equipmentbonus',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bonus_skill', to='rules.Skill'),
        ),
        migrations.AddField(
            model_name='equipmentbonus',
            name='spell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bonus_spell', to='spells.Spell'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='base_damage_type',
            field=models.ManyToManyField(help_text='What kind of damage is done by the weapon.', related_name='weapon_base_damage_types', to='rules.DamageType'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='properties',
            field=models.ManyToManyField(related_name='weapon_properties', to='equipment.WeaponProperty'),
        ),
    ]
