# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the spell.', max_length=100, unique=True)),
                ('school', models.CharField(choices=[('AB', 'Abjuration'), ('CO', 'Conjuration'), ('DI', 'Divination'), ('EN', 'Enchantment'), ('EV', 'Evocation'), ('IL', 'Illusion'), ('NE', 'Necromancy'), ('TR', 'Transmutation')], help_text='Magical school for the spell.', max_length=2)),
                ('level', models.SmallIntegerField(choices=[(0, 'Cantrip'), (1, '1st-level'), (2, '2nd-level'), (3, '3rd-level'), (4, '4th-level'), (5, '5th-level'), (6, '6th-level'), (7, '7th-level'), (8, '8th-level'), (9, '9th-level')], help_text='Level of the spell.', max_length=1)),
                ('cast_time', models.CharField(choices=[('AC', '1 Action'), ('BA', '1 Bonus Action'), ('RE', '1 Reaction'), ('1M', '1 Minute'), ('10', '10 Minutes'), ('1H', '1 Hour'), ('8H', '8 Hours'), ('12', '12 Hours'), ('24', '24 Hours')], help_text='Cast time for a spell.', max_length=2)),
                ('distance', models.SmallIntegerField(help_text='Distance the spell can be cast up to in feet; 0 = self.')),
                ('duration', models.SmallIntegerField(help_text='Duration of the spell in minutes; 0 = instant, -1 = infinite (until dispelled).')),
                ('concentration', models.BooleanField(default=False, help_text='Whether a spell requires concentration.')),
                ('components', models.CharField(choices=[('V', 'Verbal'), ('S', 'Somatic'), ('M', 'Material')], help_text='Which of the three types of components are required for a spell.', max_length=1)),
                ('materials', models.CharField(help_text='Which specific materials does the spell require.', max_length=256)),
                ('description', models.TextField(help_text='Full description of the spell.')),
                ('save_type', models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('CON', 'Constitution'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma'), ('NON', 'None')], help_text='Which save ability is used if any.', max_length=3)),
                ('damage_dice_number', models.SmallIntegerField(help_text='Ex: Xd6 + 1.')),
                ('damage_dice_size', models.SmallIntegerField(help_text='Ex: 1dX + 1.')),
                ('damage_dice_bonus', models.SmallIntegerField(blank=True, help_text='Ex: 1d6 + X.', null=True)),
                ('damage_type', models.CharField(choices=[('AC', 'Acid'), ('BL', 'Bludgeoning'), ('CO', 'Cold'), ('FI', 'Fire'), ('FO', 'Force'), ('LI', 'Lightning'), ('NE', 'Necrotic'), ('PI', 'Piercing'), ('PO', 'Poison'), ('PS', 'Psychic'), ('RA', 'Radiant'), ('SL', 'Slashing'), ('TH', 'Thunder')], help_text='What kind of damage is done by the spell.', max_length=2)),
                ('targets', models.SmallIntegerField(blank=True, help_text='Number of possible targets (usually not used).', null=True)),
                ('higher_level_damage', models.SmallIntegerField(blank=True, help_text='Extra dice to use if cast at a higher level.', null=True)),
                ('special', models.CharField(blank=True, help_text='General special information for a spell.', max_length=100, null=True)),
                ('phb_page', models.SmallIntegerField(help_text="Between pages 211 and 289 in the Player's Handbook.")),
            ],
        ),
    ]
