# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='level',
            field=models.CharField(choices=[(0, 'Cantrip'), (1, '1st-level'), (2, '2nd-level'), (3, '3rd-level'), (4, '4th-level'), (5, '5th-level'), (6, '6th-level'), (7, '7th-level'), (8, '8th-level'), (9, '9th-level')], help_text='Level of the spell.', max_length=1),
        ),
    ]
